### ISSUE TITLE
nosetests fail on missing file for downloaded source from pypi

### ISSUE THREAD

**Issue by maxamillion** [adrienverge/yamllint#1]
I downloaded the source tarball found on [pypi](https://pypi.python.org/pypi/yamllint/0.7.2) and ran nosetests on it, it failed because of a missing file.

```
$ nosetests
...............................................................................................................................E.....
======================================================================
ERROR: Failure: OSError ([Errno 2] No such file or directory: 'tests/yaml-1.2-spec-examples')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/admiller/rpmbuild/SOURCES/yamllint-0.7.2/tests/test_spec_examples.py", line 123, in <module>
    files = os.listdir('tests/yaml-1.2-spec-examples')
OSError: [Errno 2] No such file or directory: 'tests/yaml-1.2-spec-examples'

----------------------------------------------------------------------
Ran 133 tests in 4.745s

FAILED (errors=1)
```

**Comment by adrienverge** [comment]
Thanks for reporting this @maxamillion! Should be fixed in version 1.0.0.

**Comment by maxamillion** [comment]
Awesome, thanks! As a random side note if it interests you, I'm packaging this for inclusion in Fedora. https://bugzilla.redhat.com/show_bug.cgi?id=1309907

**Comment by adrienverge** [comment]
Excellent! I'll review your package then.
