### ISSUE TITLE
Python linter.run() raise AttributeError

### ISSUE THREAD

**Issue by wrogrammer** [adrienverge/yamllint#121]
Hi, 

I try use `yamlint` with Python script.
But I'm getting AttributeError error.

Reproduce:

```
pip install yamlint
python3 ./script.py
```

```
import os
from fnmatch import fnmatch
from yamllint import linter

root = './'
pattern = "*.yml"

for path, subdirs, files in os.walk(root):
    for name in files:
        if fnmatch(name, pattern):
            gen = linter.run(os.path.join(path, name), "./config")
            errors = list(gen)
            print(errors)
```

Error: 
```
Traceback (most recent call last):
  File "script.py", line 37, in <module>
    errors = list(gen)
  File "/usr/lib/python3/dist-packages/yamllint/linter.py", line 186, in _run
    for problem in get_costemic_problems(buffer, conf):
  File "/usr/lib/python3/dist-packages/yamllint/linter.py", line 57, in get_costemic_problems
    rules = conf.enabled_rules()
AttributeError: 'str' object has no attribute 'enabled_rules'

```

With this Python script I want to find all .yml files inside sub-directories and then check them with yamlint. I want to pass my config file.

**Comment by adrienverge** [comment]
Hi,

Please look at [the docs](https://yamllint.readthedocs.io/en/stable/development.html#yamllint.linter.run): *`conf` should be a yamllint configuration object`*.
