### ISSUE TITLE
Unacceptable character #x1f44b: special characters are not allowed in "<unicode string>"

### ISSUE THREAD

**Issue by butaca** [adrienverge/yamllint#270]
yamllint 1.23.0
Python 3.5.3
Raspbian GNU/Linux 9 (stretch)

```
Traceback (most recent call last):
  File "/usr/local/bin/yamllint", line 10, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.5/dist-packages/yamllint/cli.py", line 186, in run
    no_warn=args.no_warnings)
  File "/usr/local/lib/python3.5/dist-packages/yamllint/cli.py", line 92, in show_problems
    for problem in problems:
  File "/usr/local/lib/python3.5/dist-packages/yamllint/linter.py", line 198, in _run
    syntax_error = get_syntax_error(buffer)
  File "/usr/local/lib/python3.5/dist-packages/yamllint/linter.py", line 179, in get_syntax_error
    list(yaml.parse(buffer, Loader=yaml.BaseLoader))
  File "/usr/local/lib/python3.5/dist-packages/yaml/__init__.py", line 35, in parse
    loader = Loader(stream)
  File "/usr/local/lib/python3.5/dist-packages/yaml/loader.py", line 14, in __init__
    Reader.__init__(self, stream)
  File "/usr/local/lib/python3.5/dist-packages/yaml/reader.py", line 74, in __init__
    self.check_printable(stream)
  File "/usr/local/lib/python3.5/dist-packages/yaml/reader.py", line 144, in check_printable
    'unicode', "special characters are not allowed")
yaml.reader.ReaderError: unacceptable character #x1f44b: special characters are not allowed
  in "<unicode string>", position 7
```

Example file (utf-8)

```
---
m: 👋

```

**Comment by lucbas** [comment]
Facing the same issues with emojis in the filename.

**Comment by adrienverge** [comment]
@butaca isn't it a duplicate of https://github.com/adrienverge/yamllint/issues/48? Can you check the version of PyYAML you have?

**Comment by butaca** [comment]
Another package forced an older version of PyYAML 🤦‍♂️
Updating PyYAML fixed the issue, sorry for the noise.
