### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by mgedmin** [adrienverge/yamllint#274]
I noticed that my vim stopped highlighting YAML syntax errors.  I ran yamllint directly on a file I was editing and saw

```
Traceback (most recent call last):
  File "/home/mg/.local/bin/yamllint", line 8, in <module>
    sys.exit(run())
  File "/home/mg/.local/pipx/venvs/yamllint/lib/python3.8/site-packages/yamllint/cli.py", line 168, in run
    conf = YamlLintConfig(file=user_global_config)
  File "/home/mg/.local/pipx/venvs/yamllint/lib/python3.8/site-packages/yamllint/config.py", line 42, in __init__
    self.parse(content)
  File "/home/mg/.local/pipx/venvs/yamllint/lib/python3.8/site-packages/yamllint/config.py", line 83, in parse
    for rule in self.rules:
TypeError: 'NoneType' object is not iterable
```

Turns out this was caused by my `~/.config/yamllint/config` containing

```yaml
extends: relaxed
rules:
line-length:
  max: 200
```

I'm pretty sure this used to work before I did some pip upgrades.

I fixed my problem by changing the config to explicitly set `rules: []`, but I wonder if you'd want to catch this kind of type error in the YAML config and produce better error messages?  Or even allow `null` values and treat them as empty lists/dicts?

**Comment by adrienverge** [comment]
Hi Marius,

I'm glad you managed to get it to work again :+1: 

If using an empty `rules:` once worked, it was a hidden feature that was never meant to exist. For clarity and consistency, I think it's better to stick to what `rules` is (a dict). I agree a more friendly error message would be better.

**Comment by mgedmin** [comment]
Oh, it's a dict!  I'll go and fix my config again, before stricter typechecking breaks my editor plugins, again :)

**Comment by adrienverge** [comment]
Hehe. You can see an example of a full configuration here: https://yamllint.readthedocs.io/en/stable/configuration.html#default-configuration
