### ISSUE TITLE
locale.Error: unsupported locale setting

### ISSUE THREAD

**Issue by madrover** [adrienverge/yamllint#286]
Hi
There is some locale related issue with the just released 1.24.0 version see:

```
$ uname -a
Darwin miquel-mac.binihome.local 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
$ python3 --version
Python 3.8.3
$ export | grep LC_
LC_ALL=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
$ pip3 install yamllint==1.23.0
Requirement already satisfied: yamllint==1.23.0 in /usr/local/lib/python3.8/site-packages (1.23.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.8/site-packages (from yamllint==1.23.0) (5.3.1)
Requirement already satisfied: pathspec>=0.5.3 in /usr/local/lib/python3.8/site-packages (from yamllint==1.23.0) (0.8.0)
$ yamllint .
$ pip3 install yamllint==1.24.0
Collecting yamllint==1.24.0
  Using cached yamllint-1.24.0-py2.py3-none-any.whl (59 kB)
Requirement already satisfied: pathspec>=0.5.3 in /usr/local/lib/python3.8/site-packages (from yamllint==1.24.0) (0.8.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.8/site-packages (from yamllint==1.24.0) (5.3.1)
Installing collected packages: yamllint
  Attempting uninstall: yamllint
    Found existing installation: yamllint 1.23.0
    Uninstalling yamllint-1.23.0:
      Successfully uninstalled yamllint-1.23.0
Successfully installed yamllint-1.24.0
$ yamllint .
Traceback (most recent call last):
  File "/usr/local/bin/yamllint", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.8/site-packages/yamllint/cli.py", line 179, in run
    locale.setlocale(locale.LC_ALL, conf.locale)
  File "/usr/local/Cellar/python@3.8/3.8.3_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/locale.py", line 608, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

I'll revert to 1.23.0 for now...

Thanks!

**Comment by madrover** [comment]
Closing as duplicated to #285
