### ISSUE TITLE
[Bug] NoneType provided to format string during intention check

### ISSUE THREAD

**Issue by crashvb** [adrienverge/yamllint#432]
When executing the following command:

```bash
python -m yamllint -d "{extends: default, rules: {indentation: {indent-sequences: false}, line-length: {max: 120}}}" *.yml
```

... against the following file (`jobs.yml`):

```bash
---
jobs:
- script: |
    pipelineJob("/job-seed")
    {
      definition
      {
        cpsScm
        {
          lightweight(true)
          scm
          {
            git
            {
              remote
              {
                url("string")
                credentials(string)
              }
              branch("*/master")
              browser
              {
                stash("string")
              }
              extensions
              {
                cleanBeforeCheckout()
                cloneOptions
                {
                  noTags(true)
                  shallow(true)
                }
              }
            }
          }
          scriptPath("Jenkinsfile")
        }
      }
      description("configuration-as-code")
      logRotator(-1, 30)
      properties
      {
        disableConcurrentBuilds()
      }
      triggers
      {
        cron("H/15 * * * *")
        scm("")
      }
  }

```

... the following error occurs:

```bash
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.8.3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/user/.pyenv/versions/3.8.3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/repo/.venv/lib/python3.8/site-packages/yamllint/__main__.py", line 4, in <module>
    run()
  File "/home/user/repo/.venv/lib/python3.8/site-packages/yamllint/cli.py", line 210, in run
    prob_level = show_problems(problems, file, args_format=args.format,
  File "/home/user/repo/.venv/lib/python3.8/site-packages/yamllint/cli.py", line 106, in show_problems
    for problem in problems:
  File "/home/user/repo/.venv/lib/python3.8/site-packages/yamllint/linter.py", line 203, in _run
    for problem in get_cosmetic_problems(buffer, conf, filepath):
  File "/home/user/repo/.venv/lib/python3.8/site-packages/yamllint/linter.py", line 140, in get_cosmetic_problems
    for problem in rule.check(rule_conf,
  File "/home/user/repo/.venv/lib/python3.8/site-packages/yamllint/rules/indentation.py", line 580, in check
    for problem in _check(conf, token, prev, next, nextnext, context):
  File "/home/user/repo/.venv/lib/python3.8/site-packages/yamllint/rules/indentation.py", line 346, in _check
    'wrong indentation: expected %d but found %d' %
TypeError: %d format: a number is required, not NoneType
make: *** [makefile:13: test-yaml] Error 1
```

**Comment by adrienverge** [comment]
Hello,

This example file is not valid YAML, and crashes the Python loader (that yamllint uses) because of its last line `}`:
```
$ python -c 'import yaml; yaml.load(open("jobs.yml"))'
...
yaml.parser.ParserError: while parsing a block mapping
  in "<stdin>", line 3, column 3
expected <block end>, but found '}'
  in "<stdin>", line 50, column 3
```

I agree it would be better if yamllint didn't crash on such a file, and report a `syntax error` problem instead. Contributions are welcome.

**Comment by crashvb** [comment]
Oops, copy / paste error. I just verified the error occurs when the trailing brace is included; I've updated the original comment, it should now be possible to reproduce the error.

**Comment by crashvb** [comment]
No problem; I completely understand ;) ...

**foo.yml** (with intentionally misaligned trailing brace):
```yaml
---
jobs:
- script: |
    pipelineJob("/job-seed")
    {
   }
```

**Command execution**:
```bash
python -m yamllint -d "{extends: default, rules: {indentation: {indent-sequences: false}, line-length: {max: 120}}}" *.yml
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.8.3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/user/.pyenv/versions/3.8.3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/repo/.venv/lib/python3.8/site-packages/yamllint/__main__.py", line 4, in <module>
    run()
  File "/home/user/repo/.venv/lib/python3.8/site-packages/yamllint/cli.py", line 210, in run
    prob_level = show_problems(problems, file, args_format=args.format,
  File "/home/user/repo/.venv/lib/python3.8/site-packages/yamllint/cli.py", line 106, in show_problems
    for problem in problems:
  File "/home/user/repo/.venv/lib/python3.8/site-packages/yamllint/linter.py", line 203, in _run
    for problem in get_cosmetic_problems(buffer, conf, filepath):
  File "/home/user/repo/.venv/lib/python3.8/site-packages/yamllint/linter.py", line 140, in get_cosmetic_problems
    for problem in rule.check(rule_conf,
  File "/home/user/repo/.venv/lib/python3.8/site-packages/yamllint/rules/indentation.py", line 580, in check
    for problem in _check(conf, token, prev, next, nextnext, context):
  File "/home/user/repo/.venv/lib/python3.8/site-packages/yamllint/rules/indentation.py", line 346, in _check
    'wrong indentation: expected %d but found %d' %
TypeError: %d format: a number is required, not NoneType
```

After patching **yamllint/rules/indentation.py** ...:
```diff
 336         if isinstance(token, (yaml.FlowMappingEndToken,
 337                               yaml.FlowSequenceEndToken)):
 338             expected = context['stack'][-1].line_indent
+339             if expected is None:
+340                 expected = 0
 341         elif (context['stack'][-1].type == KEY and
 342                 context['stack'][-1].explicit_key and
 343                 not isinstance(token, yaml.ValueToken)):
 344             expected = detect_indent(expected, token)
```

...It changes to this:
```bash
python -m yamllint -d "{extends: default, rules: {indentation: {indent-sequences: false}, line-length: {max: 120}}}" *.yml
foo.yml
  6:4       error    syntax error: expected <block end>, but found '}' (syntax)

```

**Comment by adrienverge** [comment]
Very clear now, thanks :wink: :+1: 

So do you agree the YAML file is invalid, and cannot be parsed by any YAML parsing library? If yes, what do you think about my answer and proposal from https://github.com/adrienverge/yamllint/issues/432#issuecomment-1005848412?

**Comment by crashvb** [comment]
Yes, I agree that it is not valid YAML, and I am neutral as to reporting it as a syntax error. I was more opening the issue related to type safety around the `expected` variable being provided to the format string.

I'm not sure if it's pythonic or not to actively correct for this, or if a linter should be doing syntax checks ... however, from an end-user perspective it's not clear what about the YAML file causes the exception to be raised without debugging.

**Comment by adrienverge** [comment]
In my opinion, even a linter should avoid handling unexpected types, and print a clear error message to users. So we should actively correct for this.

**Comment by swalchemist** [comment]
I just used yamllint for the first time, and saw it abort with a similar error:

```
→ cat /tmp/foo
---
foo-key: |
 {
}

→ yamllint /tmp/foo
Traceback (most recent call last):
  File "/usr/local/bin/yamllint", line 33, in <module>
    sys.exit(load_entry_point('yamllint==1.29.0', 'console_scripts', 'yamllint')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yamllint/1.29.0/libexec/lib/python3.11/site-packages/yamllint/cli.py", line 228, in run
    prob_level = show_problems(problems, file, args_format=args.format,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yamllint/1.29.0/libexec/lib/python3.11/site-packages/yamllint/cli.py", line 113, in show_problems
    for problem in problems:
  File "/usr/local/Cellar/yamllint/1.29.0/libexec/lib/python3.11/site-packages/yamllint/linter.py", line 200, in _run
    for problem in get_cosmetic_problems(buffer, conf, filepath):
  File "/usr/local/Cellar/yamllint/1.29.0/libexec/lib/python3.11/site-packages/yamllint/linter.py", line 137, in get_cosmetic_problems
    for problem in rule.check(rule_conf,
  File "/usr/local/Cellar/yamllint/1.29.0/libexec/lib/python3.11/site-packages/yamllint/rules/indentation.py", line 583, in check
    yield from _check(conf, token, prev, next, nextnext, context)
  File "/usr/local/Cellar/yamllint/1.29.0/libexec/lib/python3.11/site-packages/yamllint/rules/indentation.py", line 344, in _check
    if expected < 0:
       ^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

I get exactly the same output with the file posted by @crashvb on January 10. I'm using Mac OS 13, yamllint 1.29.0. Any time I get an error like this, I think it indicates a bug.

With a small change, I see that yamllint can give me the kind of error I was hoping for:

```
→ cat /tmp/foo
---
foo-key:
 {
}

→ yamllint /tmp/foo
/tmp/foo
  4:1       error    wrong indentation: expected 1 but found 0  (indentation)
```
