### ISSUE TITLE
Crashes on encountering emojis

### ISSUE THREAD

**Issue by adamchainz** [adrienverge/yamllint#48]
Apparently PyYAML just crashes when loading emoji, but it's not clear why:

```
$ echo 💩 > test.yml
$ yamllint test.yml
Traceback (most recent call last):
  File "/usr/local/bin/yamllint", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/site-packages/yamllint/cli.py", line 119, in run
    for problem in linter.run(f, conf):
  File "/usr/local/lib/python2.7/site-packages/yamllint/linter.py", line 184, in _run
    syntax_error = get_syntax_error(buffer)
  File "/usr/local/lib/python2.7/site-packages/yamllint/linter.py", line 169, in get_syntax_error
    list(yaml.parse(buffer, Loader=yaml.BaseLoader))
  File "/usr/local/lib/python2.7/site-packages/yaml/__init__.py", line 34, in parse
    loader = Loader(stream)
  File "/usr/local/lib/python2.7/site-packages/yaml/loader.py", line 14, in __init__
    Reader.__init__(self, stream)
  File "/usr/local/lib/python2.7/site-packages/yaml/reader.py", line 79, in __init__
    self.determine_encoding()
  File "/usr/local/lib/python2.7/site-packages/yaml/reader.py", line 135, in determine_encoding
    self.update(1)
  File "/usr/local/lib/python2.7/site-packages/yaml/reader.py", line 169, in update
    self.check_printable(data)
  File "/usr/local/lib/python2.7/site-packages/yaml/reader.py", line 144, in check_printable
    'unicode', "special characters are not allowed")
yaml.reader.ReaderError: unacceptable character #xd83d: special characters are not allowed
  in "<string>", position 0
```

If there's some flag inside PyYAML that can be used to allow them, I think `yamllint` should activate it to allow it to lint the widest possible range of yaml files.

**Comment by adrienverge** [comment]
Thanks for reporting this!

I think it's related to https://github.com/yaml/pyyaml/issues/25
Any hint or help is welcome.

I'm curious about where you found emojis in YAML?

**Comment by adamchainz** [comment]
Writing cloudformation templates and someone tried to add 🤷‍♂️ in a comment.

**Comment by jayvdb** [comment]
The fix in PyYAML has been merged, but they [dont release yet](https://github.com/yaml/pyyaml/releases)  A bit of discussion regarding releasing at https://github.com/yaml/pyyaml/issues/46

Maybe switch to using [`ruamel.yaml`](https://pypi.python.org/pypi/ruamel.yaml) ; if so need to be careful about requiring the newish version.

**Comment by JamieH** [comment]
This is unfortunately still an issue, are there any plans to fix this? Happy to submit a PR switching to ruamel.yaml if that's of use?

**Comment by phpdev** [comment]
I have same issue. Is there any solution?

**Comment by adrienverge** [comment]
PyYAML 5.1 was just released, so the bug should be fixed now (by https://github.com/yaml/pyyaml/pull/63).

Could you test with this new version?

**Comment by adamchainz** [comment]
My reported test case now passes, yay! Thanks for the update @adrienverge :)

**Comment by adrienverge** [comment]
I'm glad to hear it 🙂
