### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by maltewhiite** [adrienverge/yamllint#536]
When I run yamllint like this `$ yamllint -f parsable . | /yamllint-junit.py` I get the following error: 

```
Traceback (most recent call last):
  File "/usr/bin/yamllint", line 11, in <module>
    load_entry_point('yamllint==1.26.0', 'console_scripts', 'yamllint')()
  File "/usr/lib/python3.6/site-packages/yamllint/cli.py", line 206, in run
    problems = linter.run(f, conf, filepath)
  File "/usr/lib/python3.6/site-packages/yamllint/linter.py", line 240, in run
    content = input.read()
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 290: ordinal not in range(128)
```

I have installed yamllint like this

```
dnf install yamllint -y
```

What can I do to fix this?

**Comment by andrewimeson** [comment]
1. What version of yamllint? `yamllint --version`? What distribution/version?
2. Do you still get the error if you don't pipe to that Python script?
3. Try and narrow down which file is causing the issue, and create a reduced example of that file that reproduces the problem

**Comment by maltewhiite** [comment]
```sh
$ yamllint --version
yamllint 1.26.0
```

Here is the file that causes the problem. Only after I've added "æøå" did the problem arise. 

<details><summary>yaml file that raises the error</summary>

```yaml 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: nginx
  template:
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
      - name: nginxæøå
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```

</details>

This is running in a GitLab CI test job like so:  
First we build the yamllint image in a Dockerfile

<details><summary>Dockerfile to build image we use in GitLab CI</summary>

```Dockerfile
# CentOS 7
FROM private-base-image 

# On Fedora / CentOS (note: EPEL is required on CentOS):
# https://yamllint.readthedocs.io
RUN yum install epel-release -y
RUN yum install dnf -y
RUN dnf install yamllint -y

# Install git 
RUN yum install git -y

# Copy python script for converting yamllint output to junit report.
COPY yamllint-junit.py .
RUN chmod +x yamllint-junit.py 

# Overwrite ENTRYPOINT so it works in GitLab CI 
ENTRYPOINT [""]
CMD ["yamllint", "--help"]
```

</details>

Then we have the `.gitlab-ci.yml`

We build the image, then we test it. 

<details><summary>gitlab ci pipeline</summary>

```yaml
---
# https://docs.gitlab.com/ee/ci/yaml/#include
include:
  - project: 'ci-templates'
    ref: main
    file: '.build-template.yml'

default:
  tags:
    - docker

# Set the name of the image you wish to build.
variables:
  IMAGE_NAME: yaml-lint

stages:
  - build
  - test
  - deploy

test yaml lint:
  stage: test
  # Test the image we just built
  image: ${INTERNAL_REGISTRY}/${IMAGE_NAME}:test
  variables:
    REPORT_ARTIFACT: junit.xml
  # Only run on Merge Requests, that have *.yaml file changes.
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - "**/*.yaml"
      allow_failure: true
  script:
    - yamllint --version
      # Get a list of all changed .yaml files compared to the master branch
    - git fetch
    - changed_files=$(git diff --name-only origin/$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME | grep '\.yaml$')
    - echo "${changed_files}"
    - yamllint -f parsable $changed_files | /yamllint-junit.py
  artifacts:
    when: always
    paths:
      - $REPORT_ARTIFACT
    reports:
      junit: $REPORT_ARTIFACT

```

</details>

<details><summary>CI job output </summary>

```sh
$ yamllint --version
yamllint 1.26.0
$ git fetch
From https://gitlab.dap.cfcs.dk/p-cyber/ams/docker/yamllint
   a61ef9e..40a0c79  main       -> origin/main
 + e4f76e1...eae074d malhvi-main-patch-93160 -> origin/malhvi-main-patch-93160  (forced update)
$ changed_files=$(git diff --name-only origin/$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME | grep '\.yaml$')
$ echo "${changed_files}"
test.yaml
$ yamllint -f parsable $changed_files | /yamllint-junit.py
Traceback (most recent call last):
  File "/usr/bin/yamllint", line 11, in <module>
    load_entry_point('yamllint==1.26.0', 'console_scripts', 'yamllint')()
  File "/usr/lib/python3.6/site-packages/yamllint/cli.py", line 206, in run
    problems = linter.run(f, conf, filepath)
  File "/usr/lib/python3.6/site-packages/yamllint/linter.py", line 240, in run
    content = input.read()
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 290: ordinal not in range(128)
```

</details>

**Comment by adrienverge** [comment]
Like @andrewimeson suggested, you should narrow down the issue cause to a minimalist reproduction, otherwise it's hard to help you.

You can search for your issue title ("UnicodeDecodeError") in existing issues: there are 10 of them. Please reopen this one if solutions described there do not apply in your case. Thanks!

**Comment by maltewhiite** [comment]
@adrienverge - Is this what you mean by "minimalist reproduction"? 

```sh
[root@fa8252f99582 /]# yamllint --version
yamllint 1.26.0
[root@fa8252f99582 /]# cat test.yaml 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
      - name: nginxæøå
        image: nginx:1.14.2
        ports:
        - containerPort: 80

[root@fa8252f99582 /]# yamllint -f parsable test.yaml
Traceback (most recent call last):
  File "/usr/bin/yamllint", line 11, in <module>
    load_entry_point('yamllint==1.26.0', 'console_scripts', 'yamllint')()
  File "/usr/lib/python3.6/site-packages/yamllint/cli.py", line 206, in run
    problems = linter.run(f, conf, filepath)
  File "/usr/lib/python3.6/site-packages/yamllint/linter.py", line 240, in run
    content = input.read()
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 305: ordinal not in range(128)
[root@fa8252f99582 /]# 
```

**Comment by perlpunk** [comment]
What does `locale` output?
try:
```
localedef -c -f UTF-8 -i en_US en_US.UTF-8
export LC_ALL=en_US.UTF-8
```
and then try the yamllint command again.

**Comment by maltewhiite** [comment]
> What does `locale` output? try:
> 
> ```
> localedef -c -f UTF-8 -i en_US en_US.UTF-8
> export LC_ALL=en_US.UTF-8
> ```
> 
> and then try the yamllint command again.

Holy shit, that worked!! Thanks man <3 

I booted up the container again, created the test.yaml, saw it fail, then used those two commands and then it works. Added some spaces in the output, so it is more readable. 

Will try to add this to my Dockerfile or the .gitlab-ci.yml and then hopefully that will fix it there as well. 

```sh
[root@5c99f75c68e9 bin]# nano test.yaml
[root@5c99f75c68e9 bin]# yamllint -f parsable test.yaml
Traceback (most recent call last):
  File "/usr/bin/yamllint", line 11, in <module>
    load_entry_point('yamllint==1.26.0', 'console_scripts', 'yamllint')()
  File "/usr/lib/python3.6/site-packages/yamllint/cli.py", line 206, in run
    problems = linter.run(f, conf, filepath)
  File "/usr/lib/python3.6/site-packages/yamllint/linter.py", line 240, in run
    content = input.read()
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 305: ordinal not in range(128)

[root@5c99f75c68e9 bin]# localedef -c -f UTF-8 -i en_US en_US.UTF-8
[root@5c99f75c68e9 bin]# export LC_ALL=en_US.UTF-8

[root@5c99f75c68e9 bin]# yamllint -f parsable test.yaml
test.yaml:14:3: [error] duplication of key "template" in mapping (key-duplicates)
test.yaml:20:7: [error] wrong indentation: expected 8 but found 6 (indentation)
test.yaml:24:9: [error] wrong indentation: expected 10 but found 8 (indentation)
test.yaml:25:1: [error] too many blank lines (1 > 0) (empty-lines)

[root@5c99f75c68e9 bin]# 
```

**Comment by perlpunk** [comment]
> Thanks man <3

woman.
You're welcome.
I simply searched for `python UnicodeDecodeError centos locale` and found this
