### ISSUE TITLE
Getting errors when running yamllint using pre-commit

### ISSUE THREAD

**Issue by wickedknock** [adrienverge/yamllint#556]
Getting errors when running yamllint using pre-commit using python 3.11.2 on windows :
`Check YAML files with yamllint...........................................Failed
- hook id: yamllint
- exit code: 1

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Tixsee\.cache\pre-commit\repovg5b8rur\py_env-python3\Scripts\yamllint.EXE\__main__.py", line 7, in <module>
  File "C:\Users\Tixsee\.cache\pre-commit\repovg5b8rur\py_env-python3\Lib\site-packages\yamllint\cli.py", line 224, in run
    problems = linter.run(f, conf, filepath)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tixsee\.cache\pre-commit\repovg5b8rur\py_env-python3\Lib\site-packages\yamllint\linter.py", line 233, in run
    content = input.read()
              ^^^^^^^^^^^^
  File "C:\Users\Tixsee\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 481: character maps to <undefined>
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Tixsee\.cache\pre-commit\repovg5b8rur\py_env-python3\Scripts\yamllint.EXE\__main__.py", line 7, in <module>
  File "C:\Users\Tixsee\.cache\pre-commit\repovg5b8rur\py_env-python3\Lib\site-packages\yamllint\cli.py", line 224, in run
    problems = linter.run(f, conf, filepath)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tixsee\.cache\pre-commit\repovg5b8rur\py_env-python3\Lib\site-packages\yamllint\linter.py", line 233, in run
    content = input.read()
              ^^^^^^^^^^^^
  File "C:\Users\Tixsee\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 481: character maps to <undefined>
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Tixsee\.cache\pre-commit\repovg5b8rur\py_env-python3\Scripts\yamllint.EXE\__main__.py", line 7, in <module>
  File "C:\Users\Tixsee\.cache\pre-commit\repovg5b8rur\py_env-python3\Lib\site-packages\yamllint\cli.py", line 224, in run
    problems = linter.run(f, conf, filepath)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tixsee\.cache\pre-commit\repovg5b8rur\py_env-python3\Lib\site-packages\yamllint\linter.py", line 233, in run
    content = input.read()
              ^^^^^^^^^^^^
  File "C:\Users\Tixsee\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 481: character maps to <undefined>
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Tixsee\.cache\pre-commit\repovg5b8rur\py_env-python3\Scripts\yamllint.EXE\__main__.py", line 7, in <module>
  File "C:\Users\Tixsee\.cache\pre-commit\repovg5b8rur\py_env-python3\Lib\site-packages\yamllint\cli.py", line 224, in run
    problems = linter.run(f, conf, filepath)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tixsee\.cache\pre-commit\repovg5b8rur\py_env-python3\Lib\site-packages\yamllint\linter.py", line 233, in run
    content = input.read()
              ^^^^^^^^^^^^
  File "C:\Users\Tixsee\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 481: character maps to <undefined>
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Tixsee\.cache\pre-commit\repovg5b8rur\py_env-python3\Scripts\yamllint.EXE\__main__.py", line 7, in <module>
  File "C:\Users\Tixsee\.cache\pre-commit\repovg5b8rur\py_env-python3\Lib\site-packages\yamllint\cli.py", line 224, in run
    problems = linter.run(f, conf, filepath)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tixsee\.cache\pre-commit\repovg5b8rur\py_env-python3\Lib\site-packages\yamllint\linter.py", line 233, in run
    content = input.read()
              ^^^^^^^^^^^^
  File "C:\Users\Tixsee\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 481: character maps to <undefined>
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Tixsee\.cache\pre-commit\repovg5b8rur\py_env-python3\Scripts\yamllint.EXE\__main__.py", line 7, in <module>
  File "C:\Users\Tixsee\.cache\pre-commit\repovg5b8rur\py_env-python3\Lib\site-packages\yamllint\cli.py", line 224, in run
    problems = linter.run(f, conf, filepath)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tixsee\.cache\pre-commit\repovg5b8rur\py_env-python3\Lib\site-packages\yamllint\linter.py", line 233, in run
    content = input.read()
              ^^^^^^^^^^^^
  File "C:\Users\Tixsee\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 481: character maps to <undefined>
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Tixsee\.cache\pre-commit\repovg5b8rur\py_env-python3\Scripts\yamllint.EXE\__main__.py", line 7, in <module>
  File "C:\Users\Tixsee\.cache\pre-commit\repovg5b8rur\py_env-python3\Lib\site-packages\yamllint\cli.py", line 224, in run
    problems = linter.run(f, conf, filepath)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tixsee\.cache\pre-commit\repovg5b8rur\py_env-python3\Lib\site-packages\yamllint\linter.py", line 233, in run
    content = input.read()
              ^^^^^^^^^^^^
  File "C:\Users\Tixsee\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 481: character maps to <undefined>`

**Comment by adrienverge** [comment]
I guess it's (yet another) Windows encoding problem. Please look for similar issues before opening new ones: you'll probably find solutions there. Thanks!
