### ISSUE TITLE
Not available in apt-get repositories?

### ISSUE THREAD

**Issue by hobti01** [adrienverge/yamllint#56]
Has the package been removed from the apt-get repos?
```
root@185cd0d5dccb:/# cat /etc/debian_version
8.8
root@185cd0d5dccb:/# apt-get -qq update && apt-get -qq install -y yamllint
E: Unable to locate package yamllint
```

Trying the "old version" approach also fails:
```
root@185cd0d5dccb:/# apt-get -qq install -y software-properties-common
root@185cd0d5dccb:/# add-apt-repository -y ppa:adrienverge/ppa
gpg: keyring `/tmp/tmp7819p0qh/secring.gpg' created
gpg: keyring `/tmp/tmp7819p0qh/pubring.gpg' created
gpg: requesting key 7EB83022 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmp7819p0qh/trustdb.gpg: trustdb created
gpg: key 7EB83022: public key "Launchpad PPA for Adrien Verg�" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 153, in run
    self.add_ppa_signing_key(self.ppa_path)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 250, in add_ppa_signing_key
    tmp_export_keyring, signing_key_fingerprint, tmp_keyring_dir):
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 202, in _verify_fingerprint
    got_fingerprints = self._get_fingerprints(keyring, keyring_dir)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 194, in _get_fingerprints
    output = subprocess.check_output(cmd, universal_newlines=True)
  File "/usr/lib/python3.4/subprocess.py", line 609, in check_output
    output, unused_err = process.communicate(inputdata, timeout=timeout)
  File "/usr/lib/python3.4/subprocess.py", line 947, in communicate
    stdout = _eintr_retry_call(self.stdout.read)
  File "/usr/lib/python3.4/subprocess.py", line 491, in _eintr_retry_call
    return func(*args)
  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 100: ordinal not in range(128)
```

**Comment by adrienverge** [comment]
Hi,

The `ppa:adrienverge/ppa` method is obsolete and unmaintained.

Official Debian repos, however, should work. I am not a Debian user but https://tracker.debian.org/pkg/yamllint doesn't report anything bad... Are you using Debian or Ubuntu? Can you reproduce on a different machine?

**Comment by hobti01** [comment]
Hi Adrien,

I'm using the latest debian 8 within docker, every instance has the same behaviour
```
$ docker run -it debian:8 /bin/bash
root@4585cc9e51d4:/# apt-get -qq update && apt-get -qq install -y yamllint
E: Unable to locate package yamllint
```
This is debian 8.8
```
root@4585cc9e51d4:/# lsb_release -da
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.8 (jessie)
Release:	8.8
Codename:	jessie
```

**Comment by zapashcanon** [comment]
For Jessie, it's only available in backports, see [https://packages.debian.org/search?keywords=yamllint&searchon=names&suite=all&section=all&sourceid=mozilla-search](here). To use backports, see [https://backports.debian.org/Instructions/](here). Or you can upgrade to the new stable release. ;)

**Comment by hobti01** [comment]
Thanks so much!  I guess this shows how closely I'm watching Debian releases...

I will certainly upgrade to the new stable.

I think I only [looked at the big print](https://hub.docker.com/_/debian/) and missed the release two weeks ago:
> The debian:latest tag will always point the latest stable release (which is, at the time of this writing, debian:jessie). 

which updated the tags:
> stretch, stretch-20170620, 9.0, 9, latest (stretch/Dockerfile)

I've suggested an update to the text https://github.com/docker-library/docs/pull/957
