### ISSUE TITLE
No module named 'yaml' when run by pre-commit in VSCode git commit

### ISSUE THREAD

**Issue by szinn** [adrienverge/yamllint#702]
pre-commit works fine when executed from cli on Mac.

However, when run via a commit within VSCode, getting

```Traceback (most recent call last):
  File "/Users/scotte/.cache/pre-commit/repoy1fgff94/py_env-python3.12/bin/yamllint", line 5, in <module>
    from yamllint.cli import run
  File "/Users/scotte/.cache/pre-commit/repoy1fgff94/py_env-python3.12/lib/python3.12/site-packages/yamllint/cli.py", line 22, in <module>
    from yamllint import APP_DESCRIPTION, APP_NAME, APP_VERSION, linter
  File "/Users/scotte/.cache/pre-commit/repoy1fgff94/py_env-python3.12/lib/python3.12/site-packages/yamllint/linter.py", line 19, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'```

PyYAML is installed on the system 

Thoughts?

**Comment by andrewimeson** [comment]
This issue would be better looked at from the pre-commit side. You could try deleting and recreating the pre-commit environment. Take a look at #674

**Comment by szinn** [comment]
I've done that with no change. Tried also adding PyYAML as an additional dependency with no luck. Will check the pre-commit side. Likely there's some weird python version mismatch going on

**Comment by szinn** [comment]
Running pip3 list in the .cache/pre-commit repo for yamllint does not show PyYAML as being installed. If I use that pip to install PyYAML, then the issue is resolved. It appears that the dependency for PyYAML isn't declared perhaps?

**Comment by andrewimeson** [comment]
It works for me with the following `.pre-commit-config.yaml`

```yaml
---
repos:
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [--strict]
```

```console
$ python3.12 -m venv .venv
$ source .venv/bin/activate
$ pip freeze  # No PyYAML present
$ pip install pre-commit
$ pre-commit run --all-files
yamllint.................................................................Passed
```

What version of yamllint are you targeting?
